### ISSUE TITLE
Where is the code of model SSGC?

### ISSUE THREAD

**Issue by hazdzz** [allenhaozhu/SSGC#1]
In models.py, I can find GCN and SGC, but I cannot find SSGC. Where is SSGC?

**Comment by allenhaozhu** [comment]
Sorry for my fault. This code is for the supplement materials, and thus we do not change the name for many functions based on SGC. In models.py, SGC is only a softmax, and the graph filter of SSGC is in the sgc_precompute function, which is in utils.py. Sorry to confuse you, we will fix it as soon as possible.

**Comment by allenhaozhu** [comment]
> In models.py, I can find GCN and SGC, but I cannot find SSGC. Where is SSGC?

sorry for my fault, I attached the reason in the last post.

**Comment by hazdzz** [comment]
I hope you could offer a clearer code later.

**Comment by allenhaozhu** [comment]
> I hope you could offer a clearer code later.

Sure. I will refactor codes after ICCV deadline.
